export const ROUTE_PARAM = {
  UID: ':uid',
} as const;

const ROOT_ROUTE = {
  ROOT: '/',
  ALL: '*',
  WORK_WITH_US: '/work-with-us',
  BECOME_BOOSTER: '/become-booster',
  BECOME_CURRENCY_SUPPLIER: '/become-currency-supplier',
  BECOME_CURRENCY_SELLER: '/become-currency-seller',
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  SIGNUP_DISCORD: '/auth/discord',
  PROFILE: '/profile',
  UNAUTHORIZED: '/unauthorized',
  MY_ORDERS: '/my-orders',
  GUIDES: '/guides',
  OFFERS: '/offers',
  PROMO: '/promo',
  GAMES: '/games',
  GAME_CURRENCIES: '/game-currencies',
  GAME_CURRENCIES_OFFER: '/game-currencies-offer',
  CHECKOUT: '/checkout',
  SUPPORT: '/support',
  DASHBOARD: '/dashboard',
  ABOUT_US: '/about-us',
  CONTACT_US: '/contact-us',
  REFUND_POLICY: '/refund-policy',
  PRIVACY_POLICY: '/privacy-policy',
  COOKIE_POLICY: '/cookie-policy',
  COPYRIGHT_NOTICE: '/copyright-notice',
  TERMS_AND_CONDITIONS: '/terms-and-conditions',
  CREDENTIAL_ON_FILE: '/credential-on-file',
  CONNECT_WALLET: '/connect-wallet',
} as const;

const CHECKOUT_PAGES = {
  CHECKOUT_METHOD: `${ROOT_ROUTE.CHECKOUT}/method`,
  CHECKOUT_REVIEW: `${ROOT_ROUTE.CHECKOUT}/review`,
  CHECKOUT_SUCCESS: `${ROOT_ROUTE.CHECKOUT}/success`,
  CHECKOUT_PAYMENT: `${ROOT_ROUTE.CHECKOUT}/payment`,
  CHECKOUT_BALANCE_RECHARGE: `${ROOT_ROUTE.CHECKOUT}/balance-recharge`,

  // CHECKOUT_CANCEL: `${ROOT_ROUTE.CHECKOUT}/cancel`,
} as const;
const PROFILE_PAGES = {
  ACCOUNT_INFO: `${ROOT_ROUTE.PROFILE}/account-info`,
  GENERAL_SETTINGS: `${ROOT_ROUTE.PROFILE}/general-settings`,
  TRANSACTIONS: `${ROOT_ROUTE.PROFILE}/transactions`,
  WALLET: `${ROOT_ROUTE.PROFILE}/wallet`,
  WALLET_SUCCESS: `${ROOT_ROUTE.PROFILE}/wallet/success`,
} as const;

const DB_PAGES = {
  // DB_CUSTOMER: `${ROOT_ROUTE.DASHBOARD}/customer`,
  DB_PARTNER: `${ROOT_ROUTE.DASHBOARD}/partner`,
  DB_SUPPORT: `${ROOT_ROUTE.DASHBOARD}/support`,
  DB_ADMIN: `${ROOT_ROUTE.DASHBOARD}/admin`,
} as const;

// const CUSTOMER_PAGES = {
//   CUSTOMER_ORDER: `${DB_PAGES.DB_CUSTOMER}/order`,
// } as const;

const PARTNER_SUPPLIER_PAGES = {
  PARTNER_SUPPLIER_CURRENCY_OFFERS: `${DB_PAGES.DB_PARTNER}/currency-offers`,
} as const;

const PARTNER_PAGES = {
  ...PARTNER_SUPPLIER_PAGES,
  PARTNER_ORDER: `${DB_PAGES.DB_PARTNER}/order`,
  PARTNER_CLAIM: `${DB_PAGES.DB_PARTNER}/claim`,
    PARTNER_CURRENCY_OFFERS: `${DB_PAGES.DB_PARTNER}/currency-offers`,
} as const;

const SUPPORT_PAGES = {
  SUPPORT_ORDER: `${DB_PAGES.DB_SUPPORT}/order`,
  SUPPORT_TICKETS: `${DB_PAGES.DB_SUPPORT}/tickets`,
  SUPPORT_INCOMING_ORDERS: `${DB_PAGES.DB_SUPPORT}/incoming-orders`,
} as const;
const ADMIN_PAGES = {
  ADMIN_ORDER: `${DB_PAGES.DB_ADMIN}/order`,
  ADMIN_WORK_WITH_US: `${DB_PAGES.DB_ADMIN}/work-with-us`,
  ADMIN_EMPLOYEES: `${DB_PAGES.DB_ADMIN}/employees`,
  ADMIN_TICKETS: `${DB_PAGES.DB_ADMIN}/tickets`,
  ADMIN_FINANCES: `${DB_PAGES.DB_ADMIN}/finances`,
  ADMIN_GAMES: `${DB_PAGES.DB_ADMIN}/games`,
  ADMIN_OFFERS: `${DB_PAGES.DB_ADMIN}/offers`,
  ADMIN_PROMOS: `${DB_PAGES.DB_ADMIN}/promo`,
  ADMIN_REVIEWS: `${DB_PAGES.DB_ADMIN}/reviews`,
  ADMIN_PARTNERS: `${DB_PAGES.DB_ADMIN}/partners`,
  ADMIN_CURRENCIES: `${DB_PAGES.DB_ADMIN}/currencies`,
  ADMIN_INCOMING_ORDERS: `${DB_PAGES.DB_ADMIN}/incoming-orders`,
  ADMIN_USER_MANAGER: `${DB_PAGES.DB_ADMIN}/user-manager`,
  ADMIN_PARTNER_MANAGER: `${DB_PAGES.DB_ADMIN}/partner-manager`,
} as const;

export const ROUTER_PATH = {
  ...ROOT_ROUTE,
  ...CHECKOUT_PAGES,
  ...PROFILE_PAGES,
  ...DB_PAGES,
  // ...CUSTOMER_PAGES,
  ...PARTNER_PAGES,
  ...SUPPORT_PAGES,
  ...ADMIN_PAGES,
  GUIDES_SINGLE: `${ROOT_ROUTE.GUIDES}/${ROUTE_PARAM.UID}`,
  ORDERS_SINGLE: `${ROOT_ROUTE.MY_ORDERS}/${ROUTE_PARAM.UID}`,
  SUPPORT_TICKET_SUMMARY: `${ROOT_ROUTE.SUPPORT}/${ROUTE_PARAM.UID}/summary`,
  RATE_ORDER: `${ROOT_ROUTE.MY_ORDERS}/${ROUTE_PARAM.UID}/rate`,
  RATE_CLIENT: `${ROOT_ROUTE.MY_ORDERS}/${ROUTE_PARAM.UID}/rate-client`,
  ORDER_REVIEW: `${ROOT_ROUTE.MY_ORDERS}/${ROUTE_PARAM.UID}/review`,
  GAMES_SINGLE: `${ROOT_ROUTE.GAMES}/${ROUTE_PARAM.UID}`,
  GAMES_CREATE: `${ROOT_ROUTE.GAMES}/create`,
  GAMES_EDIT: `${ROOT_ROUTE.GAMES}/${ROUTE_PARAM.UID}/edit`,
  GAME_CURRENCIES_CREATE: `${ROOT_ROUTE.GAME_CURRENCIES}/create`,
  GAME_CURRENCIES_EDIT: `${ROOT_ROUTE.GAME_CURRENCIES}/${ROUTE_PARAM.UID}/edit`,
  GAME_CURRENCIES_OFFER_CREATE: `${ROOT_ROUTE.GAME_CURRENCIES_OFFER}/create`,
  GAME_CURRENCIES_OFFER_EDIT: `${ROOT_ROUTE.GAME_CURRENCIES_OFFER}/${ROUTE_PARAM.UID}/edit`,
  PROMO_CREATE: `${ROOT_ROUTE.PROMO}/create`,
  PROMO_EDIT: `${ROOT_ROUTE.PROMO}/${ROUTE_PARAM.UID}/edit`,
  CURRENCIES_SINGLE: `${ROOT_ROUTE.GAME_CURRENCIES}/${ROUTE_PARAM.UID}`,
  OFFERS_SINGLE: `${ROOT_ROUTE.GAMES}/${ROUTE_PARAM.UID}/${ROUTE_PARAM.UID}`,
  OFFER_CREATE: `${ROOT_ROUTE.OFFERS}/create`,
  OFFER_EDIT: `${ROOT_ROUTE.OFFERS}/${ROUTE_PARAM.UID}/edit`,
} as const;

export type RouterPath = (typeof ROUTER_PATH)[keyof typeof ROUTER_PATH];
